### ISSUE TITLE
Incompatible with Netlify-CLI >= 2.0

### ISSUE THREAD

**Issue by loicteixeira** [tomdyson/wagtail-netlify#13]
Netlify deprecated their Node based CLI some time last year in favour of the Go based CLI (see #5) before doing it all in reverse. In the process, they had a complete rewrite of the Node based CLI which Wagtail Netlify is now incompatible with.

I'll go ahead and release Wagtail-Netlify v0.2 (which brings Wagtail 2.x support) with a mention that it is only compatible with Netlify-CLI < 2.0 in order to have a nice intermediary version without any breaking changes, then work on making it compatible with the new CLI and release yet another version. I don't think there is much point in supporting both version of the CLI as they are now on version 2.6.4 and probably don't care too much about the 1.2.x versions so it will be a breaking change.

**Comment by tomdyson** [comment]
Sounds good, thanks @loicteixeira!
